name: Test example negative
on:
  ## Added pull_request to register workflow from the PR.
  ## Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
  pull_request:
    branches-ignore: ['*']
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        id: current
        with:
          param1: 'false'

      - uses: nick-fields/assert-action@v1
        with:
          expected: 'false'
          actual: ${{ steps.current.outputs.result1 }}

  teardown:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
